# Copy into nginx-proxy vhost.d for your hostname, e.g. vhost.d/learnix.mikyss.ru

client_max_body_size 64m;

proxy_connect_timeout 75s;
proxy_send_timeout 3600s;
proxy_read_timeout 3600s;
send_timeout 3600s;

proxy_buffering off;
proxy_request_buffering off;
